modLoader="javafml"
loaderVersion="[40,)"
license="CC BY-NC-SA 4.0"

[[mods]]
modId="netherislands"
version="0.1"
displayName="Nether Ending"
updateJSONURL="https://raw.githubusercontent.com/North-West-Wind/NetherIslands/main/update.json"
logoFile="logo.png"
authors="NorthWestWind"
description='''
Overrides the Nether's generation. Defaults to use Floating Islands for the noise generator settings.
'''

[[dependencies.netherislands]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.netherislands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
