modLoader="javafml"
loaderVersion="[40,)"
license="CC BY-NC-SA 4.0"

[[mods]]
modId="netherislands"
version="0.1"
displayName="Nether Islands"
authors="NorthWestWind"
description='''
Generates the Nether like the End.
'''

[[dependencies.netherislands]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.netherislands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
