modLoader="javafml"
loaderVersion="[36,)"
license="CC BY-NC-SA 4.0"

[[mods]]
modId="netherislands"
version="0.2"
displayName="Nether Islands"
updateJSONURL="https://raw.githubusercontent.com/North-West-Wind/NetherIslands/main/update.json"
logoFile="logo.png"
authors="NorthWestWind"
description='''
Overrides the Nether's generation. Defaults to use Floating Islands for the noise generator settings.
'''

[[dependencies.netherislands]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.netherislands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
